[project]
name = "omeraytug-lab-sakila"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dlt[parquet,sql-database]>=1.19.1",
    "duckdb>=1.4.2",
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
]
